### ISSUE TITLE
Playground doesn't work?

### ISSUE THREAD

**Issue by AndrewRayCode** [alaingalvan/CrossShader#1]
Changing the dropdown in the playground doesn't seem to update the output, other than sometimes outputting glsl

**Comment by alaingalvan** [comment]
Hey Andrew, still polishing out the playground, just pushed an update that added syntax highlighting to the input side + improved on when the playground updates.

Still polishing things out so bear with me for now! 😅

**Comment by alaingalvan** [comment]
Going to close this one for now, seems the playground is at a pretty good state at the moment (unless I break it, in which case anyone can reply here or leave another issue if I don't immediately revert or fix it. 

Thanks!
